# Generated by Django 3.1.3 on 2020-11-18 04:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('contact_number', models.CharField(max_length=200, unique=True, verbose_name='Contact Number')),
                ('email_address', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Member Name')),
                ('contact_number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Contact Number')),
                ('email_address', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='Email')),
                ('height', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Height in Inc')),
                ('weight', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Weight in Kg')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('added_date', models.DateTimeField(blank=True, null=True, verbose_name='Added Date')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyms.company', verbose_name='Gym Name')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Trainer',
                'verbose_name_plural': 'Trainers',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Member Id')),
                ('name', models.CharField(max_length=200, verbose_name='Member Name')),
                ('contact_number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Contact Number')),
                ('email_address', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='Email')),
                ('height', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Height in Inc')),
                ('weight', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Weight in Kg')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('added_date', models.DateTimeField(blank=True, null=True, verbose_name='Added Date')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyms.company', verbose_name='Gym Name')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month', models.DateField(verbose_name='Payment Month')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment_amount', models.IntegerField(default=0, verbose_name='Payment Amount')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remark')),
                ('added_date', models.DateTimeField(blank=True, null=True, verbose_name='Added Date')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyms.company', verbose_name='Gym Name')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.member', verbose_name='Member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(blank=True, null=True, verbose_name='Expense Date')),
                ('particular', models.CharField(max_length=200, verbose_name='Particular')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remark')),
                ('added_date', models.DateTimeField(blank=True, null=True, verbose_name='Added Date')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.company', verbose_name='Gym Name')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyms.company', verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
