# Generated by Django 3.1.3 on 2020-11-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
