# Generated by Django 3.1.3 on 2020-11-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_member_member_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nid_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='NID Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Height in Inc'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Member Picture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Weight in Kg'),
        ),
    ]
